# Generated by Django 3.2 on 2021-05-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipTransactionMS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AAA',
        ),
    ]
