# Generated by Django 3.2 on 2021-05-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipTransactionMS', '0002_delete_aaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='id',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
