# Generated by Django 3.2 on 2021-05-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipTransactionMS', '0003_auto_20210508_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='minister',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
