# Generated by Django 3.2 on 2021-05-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipTransactionMS', '0004_department_minister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
