# Generated by Django 3.2 on 2021-05-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShipTransactionMS', '0007_auto_20210508_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('minister', models.CharField(default='none', max_length=255)),
                ('note', models.CharField(default='无', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('mobileNumber', models.CharField(max_length=11)),
                ('teleNumber', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipTransactionMS.department')),
            ],
        ),
    ]
