# Generated by Django 3.2 on 2021-05-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipTransactionMS', '0008_department_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('manufactureTime', models.CharField(max_length=255)),
                ('manufactureDress', models.CharField(max_length=255)),
                ('flag', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('tonnageTotal', models.CharField(max_length=255)),
                ('tonnageNet', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('power', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
