# Generated by Django 3.2 on 2021-05-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShipTransactionMS', '0009_ship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('specification', models.CharField(max_length=255)),
                ('percentage', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('originalInventory', models.IntegerField()),
                ('accumulativeStorage', models.IntegerField()),
                ('accumulativeUnStorage', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('inventoryUpperLimit', models.IntegerField()),
                ('inventoryLowerLimit', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipTransactionMS.ship')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('agreePersonnel', models.CharField(max_length=255)),
                ('isAgree', models.BooleanField(default=False)),
                ('applicationsNumber', models.IntegerField()),
                ('OperationType', models.BooleanField()),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipTransactionMS.inventory')),
            ],
        ),
    ]
