# Generated by Django 3.2 on 2021-05-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipTransactionMS', '0010_application_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='percentage',
        ),
    ]
