# Generated by Django 3.2 on 2021-05-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipTransactionMS', '0013_auto_20210509_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
