# Generated by Django 3.2 on 2021-06-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShipTransactionMS', '0014_alter_application_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('indate', models.DateField()),
                ('inspectionContent', models.CharField(max_length=255)),
                ('inspectionDate', models.DateField()),
                ('certificate', models.CharField(max_length=255)),
                ('registrationId', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipTransactionMS.ship')),
            ],
        ),
    ]
